Add missing build dependencies on boost
Without this, compilation can fail with errors like:

    /build/SMACC2-release-release-jazzy-forward_global_planner-3.1.0-2/src/forward_global_planner/forward_global_planner.cpp:28:10:
    fatal error: boost/assign.hpp: No such file or directory
       28 | #include <boost/assign.hpp>
          |          ^~~~~~~~~~~~~~~~~~